### PR TITLE
LPS-86452

### PR DESCRIPTION
**Pull request by brianikim**
Resending PR from https://github.com/pat270/liferay-portal/pull/226.

We should let browser calculate width rather than using an arbitrary percentage.

### CODE REVIEW

**Comment by pat270** [comment]
Hey @brianikim,
This doesn't fully address the layout in the image I posted in #226. Are we able to make a change like that or is it going to break things for customers.

**Comment by brianikim** [comment]
Hello @pat270 ,

Here are how the layouts look with the change proposed:

250px screen:
screenshot from 2018-10-19 13-28-25

Tablet screen:
screenshot from 2018-10-19 13-26-45

Mobile screen:
screenshot from 2018-10-19 13-25-46

The described issue from https://github.com/pat270/liferay-portal/pull/226 is only relevant once you move down to mobile screen and smaller. From my understanding, the change should not break things for the customers as we are only slightly altering the width of the actual content.

Sincerely,
Brian Kim

**Comment by pat270** [comment]
Oh this is for master, I was using 7.0.x for some reason.

**Comment by brianikim** [comment]
Hey @pat270 ,

I apologize regarding the confusion. The fix will be modified accordingly with your input reflected when the backport is attempted. Please let me know if you have any other questions or input.

Sincerely,
Brian Kim

**Comment by pat270** [comment]
New pull: https://github.com/jonmak08/liferay-portal/pull/1974

**Pull request closed without merging**
