### PR TITLE
LPS-81874

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @pat270,

Attached is an update for http://issues.liferay.com/browse/LPS-81874.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by pat270** [comment]
Hey @Brian-Hart,
I think this would work better if we didn't truncate the text since there is no alt attribute or tooltip to display the full app name. It could get confusing if there are several apps with long names that are prefixed with the same namespace. We could set a fixed `min-width`, `max-width: 10%`, `width: 100%`, and `word-wrap:break-word` on `.list-group-card-item` and do away with the truncating text. We also don't need `float: left` since `.list-group` is using the flexbox layout.

/cc @jonmak08

**Comment by jonmak08** [comment]
Hey @Brian-Hart,

Can you review @pat270's comments and make the necessary changes and send a new pull request?

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/Brian-Hart/liferay-portal/pull/1

**Pull request closed without merging**
