### PR TITLE
LPS-69125 Baseline

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Patrick,

I'm sending this pull back to you because I think that there are plenty of other places where this change might also be needed?

I have fixed the baseline issue as well.

Please see at least the following:

https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/view_file_entry.jsp#L166
https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-web/src/main/resources/META-INF/resources/edit_record.jsp#L122
https://github.com/liferay/liferay-portal/blob/master/modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/info_panel.jsp#L129
https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/wiki/wiki-web/src/main/resources/META-INF/resources/wiki_admin/node_info_panel.jsp#L61
https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/wiki/wiki-web/src/main/resources/META-INF/resources/wiki_admin/page_info_panel.jsp#L73

Thanks @pat270

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @jonmak08

**Comment by pat270** [comment]
Hey @sergiogonzalez, yes there are a lot of other places that need this fix. I was going to send them as separate pulls to each component lead since I got some push back about making sweeping changes before. Should I change all the navbars I find and send them to you? Thanks!

**Comment by sergiogonzalez** [comment]
I see... then I think it would be great to send all the changes related to the same team all at once. 

Does it make sense? Thanks!

Sergio

**Comment by pat270** [comment]
Sent to Jon, Thanks @sergiogonzalez!

New pull: https://github.com/jonmak08/liferay-portal/pull/1638

**Pull request closed without merging**
